#Numpy et Array

La bibliothèque NumPy (http://www.numpy.org/) permet d’effectuer des calculs numériques avec Python. Elle introduit une gestion facilitée des tableaux de nombres.

Il faut au départ importer le package numpy avec l’instruction suivante :

In [2]:
import numpy as np

Les tableaux - numpy.array()

Les tableaux  peuvent être créés avec numpy.array(). On utilise des crochets pour délimiter les listes d’éléments dans les tableaux.



In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])

Accès aux éléments d’un tableau :

In [6]:
print(a[0,1])

2


La fonction numpy.arange() permet de créer des listes en fonction de certain parametres:

In [7]:
m = np.arange(3, 15, 2)

La fonction numpy.linspace() permet d’obtenir un tableau 1D allant d’une valeur de départ à une valeur de fin avec un nombre donné d’éléments.

In [ ]:
np.linspace(3, 9, 10)

Pour toutes les fonctions que propose numpy, vous pouvez consulter la documentation : https://numpy.org/doc/

Le typage faible et dynamique et les limites du language interperté fait de python une solution lente pour traiter les tableaux de grande taille. 
Dans beaucoup de cas, Numpy fournit une interface pour les opérations standard qui n'implique que des données du même type. Par exemple, on peut calculer les inverses de tous les éléments d'un tableau Numpy :

In [8]:
tableau_large = np.random.randint(1, 100, size=1000000)
tableau_large = 1.0 / tableau_large

Ex 1 :  théorème des valeurs intermédiaires

1. Rappel
Soit f  une fonction continue définie sur un intervalle I et, a et b deux réels de I.Pour tout réel k compris entre f(a) et f(b), il existe au moins un réel c compris entre a et b tel que f(c)=k.

Soit f une fonction continue et strictement monotone sur un intervalle [a;b].Pour tout nombre k compris entre f(a) et f(b), l'équation f(x)=kadmet une unique solution dans l'intervalle [a;b].

2. Application
Nous considérons dans cet exercice la fonction:fdéfinie sur l'intervalle [0;1], par: f(x)=x^3+2x−2
Par la conséquence du théorème des valeurs intermédiaires :  l'équation f(x)=0 admet une unique solution x_0 dans [0;1]
* vérifier continuité et stricte monotonie de f sur [0;1]
* Pour savoir si x0 se trouve dans [0;0,5]ou dans [0,5;1], il faut vérifier si f(0) et f(0,5)  sont de mêmes signes
* proposer un algorithme de recherche pour évaluer x_0 en fonction de $N$, donner par l'utilisateur


Ex 2: Carrés magiques
Uncarré magiqueest un tableau carré de taillen×nqui contient tous les entiers de1 àn2et qui vérifieque : la somme de chaque ligne, la somme de chaque colonne, la somme de la diagonale principale et lasomme de l’anti-diagonale ont toutes la même valeur.

Pour un carré magique de taillen×n, la valeur de la somme est : S_n=n(n^2+1)/2

1. Définir un tableau pour chacun des exemples3×3 et 4×4
2. Définir une fonctionest_carre_magique(carre)qui teste si un tableaudonné est (ou pas) un carré magique
3. Génèrer de façon aléatoire des carrés contenant les entiers de1 àn2grâce à une fonctioncarre_aleatoire(n). 
4. Définir la probabilité d'obtenir un carrée magique
5. Définir une fonctionaddition_carre(carre,k)qui ajoute un entierkà tous les élé-ments du carré.


In [74]:
#Exercice 1
import math
from sympy import Symbol, S
from sympy.calculus.util import continuous_domain
from sympy.sets import Interval

def fu(x): # Avec x appartient 
    return math.pow(x, 3) + 2*x - 2

x = Symbol("x")
f = x**3 + 2*x - 2
continuous_domain(f, x, Interval(0, 1))

import numpy as np

def check_monotony(accuracy):
    domain = np.linspace(0,1, accuracy)
    monotony = [0,0,0]
    print(domain[0])
    for i in range(1, len(domain)-1):
        if fu(domain[i-1]) == fu(domain[i+1]):
            monotony[0] += 1
        elif fu(domain[i-1]) > fu(domain[i+1]):
            monotony[1] += 1
        else:
            monotony[2] += 1
    if len(domain)-2 == monotony[0]:
        print("constante")
    elif len(domain)-2 == monotony[1]:
        print("strictement decroissante")
    elif len(domain)-2 == monotony[2]:
        print("strictement croissante")
    else:
        print("Nada")

check_monotony(10000)

def check_sign(x, y):
    return True if fu(x)*f(y) > 0 else False

def dichotomie(e, n):
    x,y = (0, 1)
    diff = y-x
    i = 0
    while diff > e and i < n:
        m = (x+y)/2
        if fu(m) > 0:
            y = m
        else:
            x = m
        diff = y-x
        i += 1
    return m
            
print(dichotomie(0.001, 3)) 

0.0
strictement croissante
0.875


In [76]:
#Exercice 2
import numpy as np

array_3 = np.array([[2,7,6], [9,5,1], [4,3,8]])
array_4 = np.array([[1,6,7,4], [4,7,6,1], [8,3,2,5], [5,2,3,8]])

def test_carre_magique(array):
    #init checking val
    val = 0
    for i in range(0, len(array)):
        val += array[i][0]
    
    #Horizontaly
    check = 0
    for i in range(0, len(array)):
        for j in range(0, len(array[i])):
            check += array[i][j]
        
        if(check != val):
            return False
        else:
            check = 0
    
    #Verticaly
    for i in range(0,len(array)):
        for j in range(0,len(array)):
            check += array[j][i]
        
        if(check != val):
            return False
        else:
            check = 0
            
    #Diagonaly
    first_diag = sum(array[i][i] for i in range(0, len(array)))
    second_diag = sum(array[i][len(array)-i-1] for i in range(0,len(array)))
    
    if(first_diag != val or second_diag != val):
        return False
    return True

def carre_aleatoire(size):
    return np.random.randint(1, size**2, size=(size, size))

def proba():
    nbCarreValide = 0
    for i in range(0,10000):
        if(test_carre_magique(carre_aleatoire(2))):
            nbCarreValide+=1
    
    return nbCarreValide/10000

def addition_carre(array, n):
    return array+n

#print(test_carre_magique(array_3))
test_carre_magique(array_3)
test_carre_magique(array_4)
print(carre_aleatoire(3))
print(proba())
print(addition_carre(array_3,2))

[[2 8 7]
 [2 5 2]
 [5 2 8]]
0.036
[[ 4  9  8]
 [11  7  3]
 [ 6  5 10]]
